### ISSUE TITLE
"PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function React\Promise\resolve() after updating to 1.0.0

### ISSUE THREAD

**Issue by Tqnsls** [Icinga/icinga-packaging#345]
Our installed modules _icinga-director, icinga-reporting and icinga-vspheredb_ are failing to start after updating.
All of them are started via systemd.
Following packages were updated via _packages.icinga.com/subscription/rhel/_.

<img width="878" height="287" alt="Image" src="https://github.com/user-attachments/assets/d9b0fc0e-b65d-47cd-bb15-071f16bc6955" />

## Package-versions before update
```
icinga-director-daemon-1.11.8-1.el9.noarch
icinga-director-php-1.11.8-1.el9.noarch
icinga-director-web-1.11.8-1.el9.noarch
icinga-graphite-1.3.0-1.el9.noarch
icinga-graphite-web-1.3.0-1.el9.noarch
icinga-php-library-0.19.2-1.el9.noarch
icinga-php-thirdparty-0.15.3-1.el9.noarch
icinga-x509-1.3.2-1.el9.noarch
icinga-x509-daemon-1.3.2-1.el9.noarch
icinga-x509-php-1.3.2-1.el9.noarch
icinga-x509-web-1.3.2-1.el9.noarch
icinga2-debuginfo-2.16.1-1.el9.x86_64
icingacli-2.13.0-1.el9.noarch
icingaweb2-2.13.0-1.el9.noarch
icingaweb2-common-2.13.0-1.el9.noarch
php-icinga-2.13.0-1.el9.noarch
vim-icinga2-2.16.1-1.el9.x86_64
```

## vspheredb

```
Jul  8 14:02:18 dehze01-lsv666 systemd[1]: Started Icinga vSphereDB Daemon.
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function React\Promise\resolve(), 0 passed in /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/VsphereDbDaemon.php on line 129 and exactly 1 expected in /usr/share/icinga-php/vendor/vendor/react/promise/src/functions.php:24
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: #0 /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/VsphereDbDaemon.php(129): React\Promise\resolve()
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: #1 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/simple-daemon/src/Daemon.php(79): Icinga\Module\Vspheredb\Daemon\VsphereDbDaemon->start()
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: #6 /usr/share/icingaweb2/modules/vspheredb/application/clicommands/Command.php(53): React\EventLoop\StreamSelectLoop->run()
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: #7 /usr/share/icingaweb2/modules/vspheredb/application/clicommands/DaemonCommand.php(30): Icinga\Module\Vspheredb\Clicommands\Command->eventuallyStartMainLoop()
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: #8 /usr/share/php/Icinga/Cli/Loader.php(271): Icinga\Module\Vspheredb\Clicommands\DaemonCommand->runAction()
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: Fatal error: Uncaught ArgumentCountError: Too few arguments to function React\Promise\resolve(), 0 passed in /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/VsphereDbDaemon.php on line 129 and exactly 1 expected in /usr/share/icinga-php/vendor/vendor/react/promise/src/functions.php:24
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: #0 /usr/share/icingaweb2/modules/vspheredb/library/Vspheredb/Daemon/VsphereDbDaemon.php(129): React\Promise\resolve()
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: #1 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/simple-daemon/src/Daemon.php(79): Icinga\Module\Vspheredb\Daemon\VsphereDbDaemon->start()
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: #6 /usr/share/icingaweb2/modules/vspheredb/application/clicommands/Command.php(53): React\EventLoop\StreamSelectLoop->run()
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: #7 /usr/share/icingaweb2/modules/vspheredb/application/clicommands/DaemonCommand.php(30): Icinga\Module\Vspheredb\Clicommands\Command->eventuallyStartMainLoop()
Jul  8 14:02:18 dehze01-lsv666 icingacli[3901409]: #8 /usr/share/php/Icinga/Cli/Loader.php(271): Icinga\Module\Vspheredb\Clicommands\DaemonCommand->runAction()
Jul  8 14:02:18 dehze01-lsv666 systemd[1]: icinga-vspheredb.service: Main process exited, code=exited, status=255/EXCEPTION
Jul  8 14:02:18 dehze01-lsv666 systemd[1]: icinga-vspheredb.service: Failed with result 'exit-code'.

```

## reporting
```
Jul  8 14:04:18 dehze01-lsv666 systemd[1]: Started Icinga Reporting Scheduler.
Jul  8 14:04:18 dehze01-lsv666 icingacli[3901584]: PHP Fatal error:  Could not check compatibility between Icinga\Module\Reporting\Schedule::run(): React\Promise\ExtendedPromiseInterface and ipl\Scheduler\Contract\Task::run(): React\Promise\PromiseInterface, because class React\Promise\ExtendedPromiseInterface is not available in /usr/share/icingaweb2/modules/reporting/library/Reporting/Schedule.php on line 131
Jul  8 14:04:18 dehze01-lsv666 icingacli[3901584]: Fatal error: Could not check compatibility between Icinga\Module\Reporting\Schedule::run(): React\Promise\ExtendedPromiseInterface and ipl\Scheduler\Contract\Task::run(): React\Promise\PromiseInterface, because class React\Promise\ExtendedPromiseInterface is not available in /usr/share/icingaweb2/modules/reporting/library/Reporting/Schedule.php on line 131
Jul  8 14:04:18 dehze01-lsv666 systemd[1]: icinga-reporting.service: Main process exited, code=exited, status=255/EXCEPTION
Jul  8 14:04:18 dehze01-lsv666 systemd[1]: icinga-reporting.service: Failed with result 'exit-code'.
```

## director
```
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function React\Promise\Deferred::resolve(), 0 passed in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icinga-cli-daemon/src/IcingaCli.php on line 79 and exactly 1 expected in /usr/share/icinga-php/ipl/vendor/react/promise/src/Deferred.php:43
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: Stack trace:
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #0 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icinga-cli-daemon/src/IcingaCli.php(79): React\Promise\Deferred->resolve()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #1 /usr/share/icinga-php/ipl/vendor/evenement/evenement/src/EventEmitterTrait.php(143): gipfl\IcingaCliDaemon\IcingaCli->gipfl\IcingaCliDaemon\{closure}()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #2 /usr/share/icinga-php/vendor/vendor/react/child-process/src/Process.php(249): Evenement\EventEmitter->emit()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #3 /usr/share/icinga-php/ipl/vendor/react/event-loop/src/Timer/Timers.php(102): React\ChildProcess\Process->React\ChildProcess\{closure}()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #4 /usr/share/icinga-php/ipl/vendor/react/event-loop/src/StreamSelectLoop.php(185): React\EventLoop\Timer\Timers->tick()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #5 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(55): React\EventLoop\StreamSelectLoop->run()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #6 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Director\Daemon\BackgroundDaemon->run()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #7 /usr/share/php/Icinga/Cli/Loader.php(271): Icinga\Module\Director\Clicommands\DaemonCommand->runAction()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #8 /usr/share/php/Icinga/Application/Cli.php(167): Icinga\Cli\Loader->dispatch()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #9 /usr/share/php/Icinga/Application/Cli.php(157): Icinga\Application\Cli->dispatchOnce()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #10 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #11 {main}
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]:  thrown in /usr/share/icinga-php/ipl/vendor/react/promise/src/Deferred.php on line 43
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: Fatal error: Uncaught ArgumentCountError: Too few arguments to function React\Promise\Deferred::resolve(), 0 passed in /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icinga-cli-daemon/src/IcingaCli.php on line 79 and exactly 1 expected in /usr/share/icinga-php/ipl/vendor/react/promise/src/Deferred.php:43
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: Stack trace:
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #0 /usr/share/icingaweb2/modules/incubator/vendor/gipfl/icinga-cli-daemon/src/IcingaCli.php(79): React\Promise\Deferred->resolve()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #1 /usr/share/icinga-php/ipl/vendor/evenement/evenement/src/EventEmitterTrait.php(143): gipfl\IcingaCliDaemon\IcingaCli->gipfl\IcingaCliDaemon\{closure}()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #2 /usr/share/icinga-php/vendor/vendor/react/child-process/src/Process.php(249): Evenement\EventEmitter->emit()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #3 /usr/share/icinga-php/ipl/vendor/react/event-loop/src/Timer/Timers.php(102): React\ChildProcess\Process->React\ChildProcess\{closure}()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #4 /usr/share/icinga-php/ipl/vendor/react/event-loop/src/StreamSelectLoop.php(185): React\EventLoop\Timer\Timers->tick()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #5 /usr/share/icingaweb2/modules/director/library/Director/Daemon/BackgroundDaemon.php(55): React\EventLoop\StreamSelectLoop->run()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #6 /usr/share/icingaweb2/modules/director/application/clicommands/DaemonCommand.php(24): Icinga\Module\Director\Daemon\BackgroundDaemon->run()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #7 /usr/share/php/Icinga/Cli/Loader.php(271): Icinga\Module\Director\Clicommands\DaemonCommand->runAction()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #8 /usr/share/php/Icinga/Application/Cli.php(167): Icinga\Cli\Loader->dispatch()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #9 /usr/share/php/Icinga/Application/Cli.php(157): Icinga\Application\Cli->dispatchOnce()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #10 /usr/bin/icingacli(7): Icinga\Application\Cli->dispatch()
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]: #11 {main}
Jul  8 14:05:15 dehze01-lsv666 icingadirector[3901753]:  thrown in /usr/share/icinga-php/ipl/vendor/react/promise/src/Deferred.php on line 43
Jul  8 14:05:15 dehze01-lsv666 systemd[1]: icinga-director.service: Main process exited, code=exited, status=255/EXCEPTION
Jul  8 14:05:15 dehze01-lsv666 systemd[1]: icinga-director.service: Failed with result 'exit-code'.

```

## Your Environment

Include as many relevant details (before updating!) about the environment you experienced the problem in

* Director version (System - About): 1.11.9
* Icinga Web 2 version and modules (System - About): 2.14.0
* Icinga 2 version (`icinga2 --version`): r2.16.3-1
* Operating System and version: RHEL 9.8
* Webserver, PHP versions:
Git Commit    122c569fef6f01e0b7e1b9ca3c46ca2a29d63b03
PHP Version   8.2.31
MODULE                       VERSION
setup                        2.14.0
DirectorModifierRegexSearch  0.0.1
audit                        1.0.2
icingadb                     1.4.0
businessprocess              2.6.0
cube                         1.4.0
dependency_plugin            0.0.0
director                     1.11.9
incubator                    0.23.0
directorbranches             1.3.0
fileshipper                  1.2.0
graphite                     1.3.1
idoreports                   0.10.1
idosnap                      1.1.1
impersonate                  0.5
ipl                          v0.5.0
map                          1.1.0
migrate                      2.13.0
monitoring                   2.12.6
pdfexport                    0.11.0
pve                          0.2.0
reactbundle                  0.9.0
reporting                    1.0.4
toplevelview                 0.3.4
vision                       2.0.5
vspheredb                    1.7.1
x509                         1.4.0

**Comment by lippserd** [comment]
Hi @Tqnsls,

Thanks for the detailed report. Unfortunately, we do not yet have packages available for `reporting` and `pdfexport`, so you would have to upgrade these manually. There were compatibility-breaking changes in one of our third-party libraries, which is why we are currently rolling out upgrades across the board. For `vspheredb` and `director`, please install the `icinga-php-legacy` package, which is intended to replace the `incubator` module and contains compatibility fixes. We will try to adjust packaging and recommend installing  `icinga-php-legacy` for `director` and `vspheredb` so that it is installed automatically.

Best regards,
Eric
